#No blending, destination is overwritten.
#不混合，直接覆盖。
blend_mode = 0
[vertex_shader]
pack_id = "@core"
resource_key = "lighting"
resource_type = 23

[fragment_shader]
pack_id = "@core"
resource_key = "lighting"
resource_type = 24

[uniform_block]
pack_id = "@core"
resource_key = "lighting"
resource_type = 27

