#No blending, destination is overwritten (sky is the background).
#不混合，直接覆盖（天空是最底层背景）。
blend_mode = 0
[vertex_shader]
pack_id = "@core"
resource_key = "sky"
resource_type = 23

[fragment_shader]
pack_id = "@core"
resource_key = "sky"
resource_type = 24

[uniform_block]
pack_id = "@core"
resource_key = "sky"
resource_type = 27
